import {
  makeStyles,
  tokens,
} from "@fluentui/react-components";
import {
  CONTROL_HEIGHT_LG,
  CONTROL_HEIGHT_MD,
  PAGE_BOTTOM_SAFE_PADDING,
  SPACING,
} from "../../ui/layoutConstants";
import { NATIVE_RADIUS } from "../../ui/nativeTokens";

/** Settings 页全部 Fluent 样式（从 Settings.tsx 原样拆出）。 */
export const useStyles = makeStyles({
  container: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    overflow: "hidden",
    minWidth: 0,
    gap: SPACING.sm,
  },
  topArea: {
    display: "flex",
    flexDirection: "column",
    gap: SPACING.sm,
    flexShrink: 0,
  },
  scrollArea: {
    flex: 1,
    overflow: "auto",
    display: "flex",
    flexDirection: "column",
    gap: SPACING.md,
    paddingBottom: PAGE_BOTTOM_SAFE_PADDING,
    minHeight: 0,
    scrollbarGutter: "stable both-edges",
    "& > *": {
      flexShrink: 0,
      minHeight: 0,
    },
  },
  tabs: {
    display: "flex",
  },
  tabList: {
    width: "100%",
    "& button": {
      flex: 1,
      minWidth: 0,
      minHeight: CONTROL_HEIGHT_MD,
    },
  },
  actionRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.md,
    flexWrap: "wrap",
    padding: "8px 10px",
    borderRadius: NATIVE_RADIUS.medium,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: tokens.colorNeutralBackground2,
    position: "sticky",
    top: 0,
    zIndex: 2,
    "@media (max-width: 560px)": {
      flexDirection: "column",
      alignItems: "stretch",
    },
  },
  activeHint: {
    fontSize: "12px",
    color: tokens.colorNeutralForeground2,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    "@media (max-width: 560px)": {
      whiteSpace: "normal",
    },
  },
  actionButtons: {
    display: "flex",
    gap: SPACING.sm,
    flexWrap: "wrap",
    justifyContent: "flex-end",
    "& > button": {
      flex: "0 0 auto",
      minWidth: "96px",
    },
  },
  profilesList: {
    display: "flex",
    flexDirection: "column",
    gap: SPACING.md,
  },
  card: {
    borderRadius: NATIVE_RADIUS.medium,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    overflow: "visible",
    minWidth: 0,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    maxHeight: "none",
  },
  cardExpanded: {
    border: `1px solid ${tokens.colorNeutralStroke1}`,
  },
  cardHeader: {
    padding: "10px 12px",
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: SPACING.md,
    borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: tokens.colorNeutralBackground2,
    flexWrap: "wrap",
    flexShrink: 0,
    borderTopLeftRadius: NATIVE_RADIUS.medium,
    borderTopRightRadius: NATIVE_RADIUS.medium,
  },
  cardHeaderInfo: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    minWidth: 0,
    flex: 1,
  },
  moduleTitleRow: {
    display: "flex",
    alignItems: "center",
    gap: SPACING.sm,
    minWidth: 0,
  },
  moduleTitleIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    color: tokens.colorBrandForeground1,
    flexShrink: 0,
  },
  cardHeaderTitle: {
    fontSize: "13px",
    fontWeight: "600",
    color: tokens.colorNeutralForeground1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "normal",
  },
  cardHeaderMeta: {
    fontSize: "11px",
    color: tokens.colorNeutralForeground3,
    lineHeight: "1.4",
    whiteSpace: "normal",
  },
  cardHeaderStatus: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: SPACING.md,
    flexWrap: "wrap",
    flexShrink: 1,
    minWidth: 0,
    "@media (max-width: 520px)": {
      width: "100%",
      justifyContent: "space-between",
    },
  },
  activeTag: {
    fontSize: "12px",
    color: tokens.colorPaletteGreenForeground1,
  },
  errorTag: {
    fontSize: "12px",
    color: tokens.colorPaletteRedForeground1,
  },
  headerActions: {
    display: "flex",
    gap: SPACING.sm,
    alignItems: "center",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    "& > button": {
      flex: "0 0 auto",
      minWidth: "64px",
    },
  },
  cardContent: {
    padding: "12px",
    display: "flex",
    flexDirection: "column",
    gap: SPACING.md,
    minHeight: 0,
    overflow: "visible",
  },
  formGrid: {
    display: "grid",
    gap: SPACING.md,
    alignItems: "start",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    "@media (max-width: 520px)": {
      gridTemplateColumns: "1fr",
    },
  },
  fieldSpanFull: {
    gridColumn: "1 / -1",
  },
  inputWrapper: {
    display: "flex",
    gap: SPACING.md,
    alignItems: "center",
    "@media (max-width: 480px)": {
      flexDirection: "column",
      alignItems: "stretch",
    },
  },
  input: {
    flex: 1,
    width: "100%",
    "& input": {
      borderRadius: NATIVE_RADIUS.large,
    },
  },
  eyeButton: {
    minWidth: CONTROL_HEIGHT_LG,
    minHeight: CONTROL_HEIGHT_LG,
    borderRadius: NATIVE_RADIUS.large,
    flexShrink: 0,
    "@media (max-width: 480px)": {
      width: "100%",
    },
  },
  smallButton: {
    borderRadius: NATIVE_RADIUS.large,
    minHeight: CONTROL_HEIGHT_MD,
  },
  hint: {
    fontSize: "11px",
    color: tokens.colorNeutralForeground3,
  },
  modelDropdown: {
    minWidth: "100%",
    "& button": {
      borderRadius: NATIVE_RADIUS.large,
    },
  },
  cardActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: SPACING.md,
    flexWrap: "wrap",
    position: "sticky",
    bottom: 0,
    zIndex: 1,
    backgroundColor: tokens.colorNeutralBackground1,
    borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
    paddingTop: SPACING.sm,
    paddingBottom: SPACING.xs,
    "& > button": {
      flex: "0 0 auto",
      minWidth: "112px",
    },
  },
  primaryButton: {
    borderRadius: NATIVE_RADIUS.large,
    minHeight: CONTROL_HEIGHT_LG,
  },
  infoCard: {
    borderRadius: NATIVE_RADIUS.medium,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    borderLeft: `3px solid ${tokens.colorNeutralStroke1}`,
    backgroundColor: tokens.colorNeutralBackground1,
    padding: "10px 12px",
  },
  infoText: {
    fontSize: "12px",
    lineHeight: "1.45",
    color: tokens.colorNeutralForeground2,
  },
  infoList: {
    margin: "8px 0",
    paddingLeft: "16px",
  },
  infoListItem: {
    marginBottom: "4px",
  },
  promptMetaRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.md,
    flexWrap: "wrap",
  },
  promptTitle: {
    fontSize: "14px",
    fontWeight: "600",
    color: tokens.colorNeutralForeground1,
  },
  promptBadge: {
    fontSize: "12px",
    color: tokens.colorNeutralForeground2,
  },
  promptCard: {
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    flex: 1,
    maxHeight: "none",
  },
  promptCardContent: {
    padding: "12px",
    display: "flex",
    flexDirection: "column",
    gap: SPACING.md,
    minHeight: 0,
    flex: 1,
    overflow: "visible",
  },
  promptEditorField: {
    display: "flex",
    flexDirection: "column",
  },
  promptTextarea: {
    width: "100%",
    "& textarea": {
      minHeight: "220px",
      height: "min(48vh, 420px)",
      resize: "vertical",
      fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
      fontSize: "13px",
      lineHeight: "1.5",
    },
    "@media (max-height: 640px)": {
      "& textarea": {
        minHeight: "160px",
        height: "40vh",
      },
    },
  },
  compactTextarea: {
    width: "100%",
    "& textarea": {
      minHeight: "88px",
      resize: "vertical",
    },
  },
  iconPickerGrid: {
    display: "grid",
    gap: SPACING.sm,
    gridTemplateColumns: "repeat(auto-fit, minmax(88px, 1fr))",
    borderRadius: NATIVE_RADIUS.large,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: tokens.colorNeutralBackground1,
    padding: "8px",
    maxHeight: "280px",
    overflowY: "auto",
    scrollbarGutter: "stable",
  },
iconPickerButton: {
    appearance: "none",
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground1,
    borderRadius: NATIVE_RADIUS.large,
    minHeight: "84px",
    padding: "10px 8px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    font: "inherit",
    "@media (prefers-reduced-motion: no-preference)": {
      transitionDuration: "120ms",
      transitionProperty: "background-color, border-color, color, box-shadow",
      transitionTimingFunction: "ease",
    },
    "&:hover": {
      backgroundColor: tokens.colorNeutralBackground2,
      border: `1px solid ${tokens.colorNeutralStroke1}`,
    },
  },
  iconPickerButtonSelected: {
    border: `1px solid ${tokens.colorBrandStroke1}`,
    backgroundColor: tokens.colorBrandBackground2,
    color: tokens.colorBrandForeground1,
    boxShadow: `inset 0 0 0 1px ${tokens.colorBrandStroke1}`,
  },
  iconPickerIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  iconPickerLabel: {
    fontSize: "12px",
    lineHeight: "1.25",
    textAlign: "center",
    wordBreak: "break-word",
  },
  iconPickerCurrent: {
    display: "flex",
    alignItems: "center",
    gap: SPACING.sm,
    color: tokens.colorNeutralForeground2,
    fontSize: "12px",
  },
  optionWithIcon: {
    display: "flex",
    alignItems: "center",
    gap: SPACING.sm,
  },
  optionIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  promptActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: SPACING.md,
    flexWrap: "wrap",
    position: "sticky",
    bottom: 0,
    zIndex: 1,
    backgroundColor: tokens.colorNeutralBackground1,
    borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
    paddingTop: SPACING.sm,
    paddingBottom: SPACING.xs,
    marginTop: SPACING.sm,
    "& > button": {
      flex: "0 0 auto",
      minWidth: "112px",
    },
  },
  cardStatic: {
    maxHeight: "none",
  },
  diagnosticsGrid: {
    display: "grid",
    gap: SPACING.md,
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    "@media (max-width: 520px)": {
      gridTemplateColumns: "1fr",
    },
  },
  diagnosticTile: {
    borderRadius: NATIVE_RADIUS.medium,
    padding: "12px",
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: tokens.colorNeutralBackground1,
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    minWidth: 0,
  },
  diagnosticLabel: {
    fontSize: "12px",
    color: tokens.colorNeutralForeground3,
  },
  diagnosticValue: {
    fontSize: "14px",
    fontWeight: "600",
    color: tokens.colorNeutralForeground1,
    wordBreak: "break-word",
  },
  diagnosticMeta: {
    fontSize: "12px",
    lineHeight: "1.5",
    color: tokens.colorNeutralForeground2,
    wordBreak: "break-word",
    whiteSpace: "pre-line",
  },
  diagnosticsActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: SPACING.md,
    flexWrap: "wrap",
  },
  diagnosticsNote: {
    fontSize: "12px",
    color: tokens.colorNeutralForeground3,
    lineHeight: "1.5",
  },
  profileToolsCard: {
    borderRadius: NATIVE_RADIUS.medium,
    padding: "12px",
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: tokens.colorNeutralBackground1,
    display: "flex",
    flexDirection: "column",
    gap: SPACING.md,
  },
  profileToolsRow: {
    display: "flex",
    gap: SPACING.md,
    flexWrap: "wrap",
    "& > button": {
      flex: "0 0 auto",
      minWidth: "100px",
    },
  },
  resultBox: {
    borderRadius: NATIVE_RADIUS.medium,
    padding: "10px 12px",
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: tokens.colorNeutralBackground1,
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  resultSuccess: {
    backgroundColor: tokens.colorPaletteGreenBackground2,
    border: `1px solid ${tokens.colorPaletteGreenBorder2}`,
  },
  resultError: {
    backgroundColor: tokens.colorPaletteRedBackground2,
    border: `1px solid ${tokens.colorPaletteRedBorder2}`,
  },
  resultTitle: {
    fontSize: "13px",
    fontWeight: "600",
    color: tokens.colorNeutralForeground1,
  },
  resultDetail: {
    fontSize: "12px",
    lineHeight: "1.5",
    color: tokens.colorNeutralForeground2,
    wordBreak: "break-word",
  },
  codeList: {
    fontSize: "12px",
    lineHeight: "1.6",
    color: tokens.colorNeutralForeground2,
    wordBreak: "break-word",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
  },
});
