import { makeStyles, tokens } from "@fluentui/react-components";

export const useStyles = makeStyles({
  container: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    gap: "10px",
  },
  welcomeSection: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    padding: "16px 12px",
    textAlign: "center",
  },
  welcomeTitle: {
    fontSize: "20px",
    fontWeight: "600",
    color: tokens.colorNeutralForeground1,
    marginBottom: "6px",
  },
  welcomeSubtitle: {
    fontSize: "13px",
    color: tokens.colorNeutralForeground3,
    marginBottom: "12px",
  },
  quickActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
    justifyContent: "center",
    maxWidth: "100%",
    marginBottom: "10px",
  },
  quickActionButton: {
    borderRadius: "16px",
    padding: "6px 12px",
    fontSize: "12px",
    fontWeight: "500",
    backgroundColor: tokens.colorNeutralBackground3,
    border: "none",
    "&:hover": {
      backgroundColor: tokens.colorNeutralBackground3Hover,
    },
  },
  exampleList: {
    textAlign: "left",
    backgroundColor: tokens.colorNeutralBackground2,
    borderRadius: "12px",
    padding: "10px 12px",
    fontSize: "12px",
    lineHeight: "1.6",
    color: tokens.colorNeutralForeground2,
    maxWidth: "100%",
  },
  inputContainer: {
    backgroundColor: tokens.colorNeutralBackground3,
    borderRadius: "12px",
    padding: "8px 10px",
    marginTop: "auto",
  },
  textarea: {
    width: "100%",
    "& textarea": {
      minHeight: "72px",
      maxHeight: "120px",
      overflow: "auto !important",
      boxSizing: "border-box",
      backgroundColor: "transparent",
      border: "none",
      resize: "none",
      fontSize: "13px",
      lineHeight: "1.5",
    },
    "& .fui-Textarea__root": {
      backgroundColor: "transparent",
      border: "none",
    },
  },
  inputToolbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: "6px",
    paddingTop: "6px",
    borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
    gap: "4px",
    flexWrap: "wrap",
  },
  toolbarLeft: {
    display: "flex",
    alignItems: "center",
    gap: "2px",
    flexWrap: "wrap",
    minWidth: 0,
  },
  toolbarRight: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  toolbarButton: {
    minWidth: "28px",
    height: "28px",
    padding: "0",
    borderRadius: "6px",
  },
  toolbarButtonActive: {
    backgroundColor: "#2B579A",
    color: "#ffffff",
    "&:hover": {
      backgroundColor: "#1E3F6F",
    },
  },
  sendButton: {
    minWidth: "32px",
    height: "32px",
    padding: "0",
    borderRadius: "50%",
    backgroundColor: "#2B579A",
    color: "#ffffff",
    "&:hover": {
      backgroundColor: "#1E3F6F",
    },
    "&:disabled": {
      backgroundColor: tokens.colorNeutralBackground4,
      color: tokens.colorNeutralForegroundDisabled,
    },
  },
  sendButtonStop: {
    backgroundColor: "#D13438 !important",
    border: "1px solid #9E1F24 !important",
    color: "#ffffff !important",
    boxShadow: "0 0 0 2px rgba(209, 52, 56, 0.25)",
    "&:hover": {
      backgroundColor: "#B4282D !important",
      border: "1px solid #7F171B !important",
      boxShadow: "0 0 0 3px rgba(209, 52, 56, 0.3)",
    },
    "&:active": {
      backgroundColor: "#8F1D22 !important",
      border: "1px solid #671015 !important",
      boxShadow: "0 0 0 2px rgba(209, 52, 56, 0.35)",
    },
  },
  styleDropdown: {
    minWidth: "72px",
    "& button": {
      borderRadius: "6px",
      height: "28px",
      fontSize: "12px",
    },
  },
  clearButton: {
    minWidth: "28px",
    height: "28px",
    padding: "0",
    borderRadius: "6px",
    backgroundColor: "#D13438",
    color: "#ffffff",
    "&:hover": {
      backgroundColor: "#A4262C",
      color: "#ffffff",
    },
  },
  chatViewport: {
    position: "relative",
    flex: 1,
    minHeight: 0,
  },
  chatContainer: {
    height: "100%",
    overflow: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    padding: "4px 0",
  },
  scrollToBottomButton: {
    position: "absolute",
    right: "8px",
    bottom: "8px",
    width: "32px",
    minWidth: "32px",
    height: "32px",
    padding: "0",
    borderRadius: "50%",
    boxShadow: tokens.shadow8,
    backgroundColor: "#2B579A",
    color: "#ffffff",
    zIndex: 2,
    "&:hover": {
      backgroundColor: "#1E3F6F",
      color: "#ffffff",
    },
    "& span": {
      margin: "0",
    },
  },
  messageWrapper: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  userMessageWrapper: {
    alignItems: "flex-end",
  },
  assistantMessageWrapper: {
    alignItems: "stretch",
  },
  messageLabel: {
    fontSize: "12px",
    color: tokens.colorNeutralForeground3,
    marginBottom: "2px",
    paddingLeft: "8px",
    paddingRight: "8px",
  },
  messageBubble: {
    maxWidth: "92%",
    padding: "10px 12px",
    borderRadius: "12px",
    fontSize: "13px",
    lineHeight: "1.6",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  userBubble: {
    backgroundColor: "#2B579A",
    color: "#ffffff",
    borderBottomRightRadius: "4px",
  },
  assistantCard: {
    width: "100%",
    borderRadius: "12px",
    overflow: "hidden",
    boxShadow: tokens.shadow4,
  },
  assistantCardContent: {
    padding: "8px 12px",
  },
  assistantActions: {
    display: "flex",
    gap: "8px",
    padding: "8px 12px",
    borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: tokens.colorNeutralBackground2,
  },
  assistantContent: {
    padding: "10px",
    fontSize: "13px",
    lineHeight: "1.6",
    color: tokens.colorNeutralForeground1,
    wordBreak: "break-word",
    minHeight: "32px",
  },
  markdownContent: {
    // Make common Markdown elements look good inside the assistant card.
    "& p": { margin: "0 0 8px 0" },
    "& p:last-child": { marginBottom: 0 },
    "& h1": { margin: "0 0 10px 0", fontSize: "18px", fontWeight: "600" },
    "& h2": { margin: "0 0 10px 0", fontSize: "16px", fontWeight: "600" },
    "& h3": { margin: "0 0 8px 0", fontSize: "15px", fontWeight: "600" },
    "& h4": { margin: "0 0 8px 0", fontSize: "14px", fontWeight: "600" },
    "& h5": { margin: "0 0 8px 0", fontSize: "13px", fontWeight: "600" },
    "& h6": { margin: "0 0 8px 0", fontSize: "13px", fontWeight: "600" },
    "& ul, & ol": { margin: "0 0 8px 0", paddingLeft: "20px" },
    "& li": { marginBottom: "4px" },
    "& blockquote": {
      margin: "0 0 8px 0",
      padding: "8px 12px",
      borderLeft: `3px solid ${tokens.colorNeutralStroke2}`,
      backgroundColor: tokens.colorNeutralBackground2,
      borderRadius: "10px",
      color: tokens.colorNeutralForeground2,
    },
    "& hr": {
      border: "none",
      borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
      margin: "10px 0",
    },
    "& a": {
      color: tokens.colorBrandForeground1,
      textDecoration: "underline",
    },
    "& pre": {
      margin: "0 0 8px 0",
      padding: "10px 12px",
      backgroundColor: tokens.colorNeutralBackground2,
      borderRadius: "10px",
      overflowX: "auto",
    },
    "& code": {
      fontFamily:
        'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
      fontSize: "13px",
      backgroundColor: tokens.colorNeutralBackground2,
      borderRadius: "6px",
      padding: "2px 6px",
    },
    "& pre code": {
      backgroundColor: "transparent",
      padding: "0",
      borderRadius: "0",
    },
    "& table": {
      width: "100%",
      borderCollapse: "collapse",
      margin: "0 0 8px 0",
      fontSize: "13px",
    },
    "& th, & td": {
      border: `1px solid ${tokens.colorNeutralStroke2}`,
      padding: "6px 8px",
      verticalAlign: "top",
    },
    "& th": {
      backgroundColor: tokens.colorNeutralBackground2,
      fontWeight: "600",
    },
  },
  markdownEditor: {
    width: "100%",
    "& textarea": {
      minHeight: "120px",
      maxHeight: "240px",
      overflow: "auto !important",
      fontSize: "13px",
      lineHeight: "1.6",
      fontFamily:
        'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    },
  },
  actionButton: {
    borderRadius: "8px",
    flex: 1,
  },
  thinkingSection: {
    borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
  },
  thinkingHeader: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 12px",
    cursor: "pointer",
    backgroundColor: tokens.colorNeutralBackground2,
    "&:hover": {
      backgroundColor: tokens.colorNeutralBackground3,
    },
  },
  thinkingIcon: {
    color: tokens.colorBrandForeground1,
  },
  thinkingLabel: {
    fontSize: "12px",
    fontWeight: "500",
    color: tokens.colorNeutralForeground2,
    flex: 1,
  },
  thinkingContent: {
    padding: "8px 10px",
    backgroundColor: tokens.colorNeutralBackground1,
    fontSize: "12px",
    lineHeight: "1.5",
    color: tokens.colorNeutralForeground2,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    maxHeight: "150px",
    overflow: "auto",
    borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
  },
  toolPanel: {
    borderRadius: "12px",
    padding: "12px",
    backgroundColor: tokens.colorNeutralBackground2,
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  toolItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "12px",
    color: tokens.colorNeutralForeground2,
  },
  toolResultContent: {
    fontSize: "12px",
    color: tokens.colorNeutralForeground2,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  statusBar: {
    borderRadius: "10px",
    padding: "8px 12px",
    backgroundColor: tokens.colorNeutralBackground2,
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "12px",
    color: tokens.colorNeutralForeground2,
  },
  planPanel: {
    borderRadius: "10px",
    padding: "8px 10px",
    backgroundColor: tokens.colorNeutralBackground2,
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    flexShrink: 0,
  },
  planPanelHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "8px",
  },
  planPanelHeaderLeft: {
    display: "flex",
    alignItems: "baseline",
    gap: "8px",
    flexWrap: "wrap",
  },
  planPanelTitle: {
    fontSize: "12px",
    fontWeight: "600",
    color: tokens.colorNeutralForeground1,
  },
  planPanelMeta: {
    fontSize: "12px",
    color: tokens.colorNeutralForeground2,
  },
  planPanelContent: {
    borderRadius: "8px",
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: tokens.colorNeutralBackground1,
    padding: "6px 8px",
    maxHeight: "120px",
    overflowY: "auto",
    overflowX: "hidden",
    overscrollBehaviorY: "contain",
  },
  planPanelToggle: {
    minWidth: "52px",
    height: "24px",
    borderRadius: "6px",
    "& span": {
      fontSize: "12px",
    },
  },
  planStageItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: "8px",
    padding: "2px 0",
  },
  planStageItemDone: {
    "& span": {
      color: tokens.colorNeutralForeground3,
    },
  },
  planStageCheck: {
    fontSize: "12px",
    lineHeight: "1.4",
    minWidth: "14px",
  },
  planStageText: {
    fontSize: "12px",
    lineHeight: "1.5",
    color: tokens.colorNeutralForeground1,
    wordBreak: "break-word",
  },
  planPanelStatus: {
    fontSize: "12px",
    color: tokens.colorNeutralForeground2,
  },
  statusSuccess: {
    color: tokens.colorPaletteGreenForeground1,
  },
  statusError: {
    color: tokens.colorPaletteRedForeground1,
  },
  statusWarning: {
    color: tokens.colorPaletteYellowForeground1,
  },
  statusRetrying: {
    color: tokens.colorBrandForeground1,
  },
});
