import type { ComponentType } from "react";
import {
  Apps24Regular,
  Book24Regular,
  BrainCircuit24Regular,
  Calendar24Regular,
  Camera24Regular,
  Chat24Regular,
  ChatSparkle24Regular,
  ClipboardTask24Regular,
  Code24Regular,
  Compose24Regular,
  DataBarHorizontal24Regular,
  Document24Regular,
  DocumentText24Regular,
  Edit24Regular,
  Folder24Regular,
  Globe24Regular,
  Heart24Regular,
  Home24Regular,
  Image24Regular,
  Lightbulb24Regular,
  Mail24Regular,
  Note24Regular,
  Notebook24Regular,
  Pen24Regular,
  People24Regular,
  PersonLightbulb24Regular,
  Receipt24Regular,
  Rocket24Regular,
  ScanText24Regular,
  Search24Regular,
  Sparkle24Regular,
  Star24Regular,
  Table24Regular,
  Tag24Regular,
  Target24Regular,
  TasksApp24Regular,
  TextBulletList24Regular,
  TextEditStyle24Regular,
  TextQuote24Regular,
  SlideText24Regular,
  Translate24Regular,
  TextGrammarCheckmark24Regular,
  TextBulletListSquare24Regular,
  TextExpand24Regular,
  Wand24Regular,
  TextDescription24Regular,
  TextAlignLeft24Regular,
  Settings24Regular,
} from "@fluentui/react-icons";
import type { AssistantModuleIconKey } from "./assistantModuleService";

export const ASSISTANT_MODULE_ICON_OPTIONS: Array<{
  key: AssistantModuleIconKey;
  label: string;
  Icon: ComponentType;
}> = [
  { key: "agent", label: "智能星火", Icon: Sparkle24Regular },
  { key: "polish", label: "润色编辑", Icon: TextEditStyle24Regular },
  { key: "translate", label: "翻译", Icon: Translate24Regular },
  { key: "grammar", label: "语法检查", Icon: TextGrammarCheckmark24Regular },
  { key: "summarize", label: "摘要列表", Icon: TextBulletListSquare24Regular },
  { key: "continue", label: "续写展开", Icon: TextExpand24Regular },
  { key: "generate", label: "魔法棒", Icon: Wand24Regular },
  { key: "description", label: "文本说明", Icon: TextDescription24Regular },
  { key: "format", label: "排版", Icon: TextAlignLeft24Regular },
  { key: "settings", label: "设置", Icon: Settings24Regular },
  { key: "search", label: "搜索", Icon: Search24Regular },
  { key: "document", label: "文档", Icon: Document24Regular },
  { key: "document_text", label: "文本文档", Icon: DocumentText24Regular },
  { key: "book", label: "书籍", Icon: Book24Regular },
  { key: "notebook", label: "笔记本", Icon: Notebook24Regular },
  { key: "note", label: "便签", Icon: Note24Regular },
  { key: "clipboard_task", label: "任务清单", Icon: ClipboardTask24Regular },
  { key: "pen", label: "钢笔", Icon: Pen24Regular },
  { key: "edit", label: "编辑", Icon: Edit24Regular },
  { key: "compose", label: "撰写", Icon: Compose24Regular },
  { key: "chat", label: "对话", Icon: Chat24Regular },
  { key: "chat_sparkle", label: "智能对话", Icon: ChatSparkle24Regular },
  { key: "code", label: "代码", Icon: Code24Regular },
  { key: "data", label: "数据", Icon: DataBarHorizontal24Regular },
  { key: "table", label: "表格", Icon: Table24Regular },
  { key: "target", label: "目标", Icon: Target24Regular },
  { key: "lightbulb", label: "灵感", Icon: Lightbulb24Regular },
  { key: "brain", label: "思考", Icon: BrainCircuit24Regular },
  { key: "apps", label: "应用", Icon: Apps24Regular },
  { key: "rocket", label: "推进", Icon: Rocket24Regular },
  { key: "globe", label: "全球", Icon: Globe24Regular },
  { key: "people", label: "团队", Icon: People24Regular },
  { key: "mail", label: "邮件", Icon: Mail24Regular },
  { key: "calendar", label: "日程", Icon: Calendar24Regular },
  { key: "image", label: "图片", Icon: Image24Regular },
  { key: "camera", label: "相机", Icon: Camera24Regular },
  { key: "folder", label: "文件夹", Icon: Folder24Regular },
  { key: "home", label: "主页", Icon: Home24Regular },
  { key: "star", label: "星标", Icon: Star24Regular },
  { key: "heart", label: "收藏", Icon: Heart24Regular },
  { key: "tag", label: "标签", Icon: Tag24Regular },
  { key: "receipt", label: "摘要单", Icon: Receipt24Regular },
  { key: "tasks", label: "任务应用", Icon: TasksApp24Regular },
  { key: "slide_text", label: "标题页", Icon: SlideText24Regular },
  { key: "text_bullet", label: "列表文本", Icon: TextBulletList24Regular },
  { key: "text_quote", label: "引用文本", Icon: TextQuote24Regular },
  { key: "person_lightbulb", label: "顾问", Icon: PersonLightbulb24Regular },
  { key: "scan", label: "扫描文本", Icon: ScanText24Regular },
  { key: "custom", label: "通用", Icon: Wand24Regular },
];
