import DOMPurify from "dompurify";

const WORD_HTML_TAGS = [
  "div", "p", "br", "strong", "b", "em", "i", "del", "s", "u",
  "code", "pre", "blockquote", "ul", "ol", "li", "table", "thead",
  "tbody", "tr", "th", "td", "a", "hr", "h1", "h2", "h3", "h4",
  "h5", "h6", "span",
];

const WORD_HTML_ATTRIBUTES = [
  "href", "title", "colspan", "rowspan", "style", "start", "type",
];

/**
 * Keep the HTML handed to Word small and predictable. In production this runs
 * in the task-pane browser. The no-DOM fallback exists for Bun unit tests and
 * server-side tooling; callers there only pass HTML generated by our renderer.
 */
export function sanitizeWordHtml(html: string): string {
  const source = typeof html === "string" ? html : String(html ?? "");
  if (typeof DOMPurify.sanitize !== "function") return source;

  return DOMPurify.sanitize(source, {
    ALLOWED_TAGS: WORD_HTML_TAGS,
    ALLOWED_ATTR: WORD_HTML_ATTRIBUTES,
    ALLOW_DATA_ATTR: false,
    ALLOW_ARIA_ATTR: false,
    ALLOWED_URI_REGEXP: /^(?:(?:https?|mailto|tel):|#)/i,
  });
}
